version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
  
  greenplum:
    image: docker.io/greenplum/greenplum-database
    container_name: greenplum
    ports:
      - "5432:5432"

  citus:
    image: citusdata/citus
    container_name: citus
    ports:
      - "5432:5432"

  airbyte:
    image: airbyte/server
    container_name: airbyte
    ports:
      - "8000:8000"

  metabase:
    image: metabase/metabase
    container_name: metabase
    ports:
      - "3000:3000"
