version: '3'

services:
  # ===========================
  # ✅ Multi-Node ZooKeeper
  # ===========================
  zookeeper-1:
    image: localhost:5000/zookeeper
    container_name: zookeeper-1
    hostname: zookeeper-1
    restart: always
    networks:
      - clickhouse-net
    ports:
      - "21811:2181"
    volumes:
      - ./config/zoo/zoo.cfg:/conf/zoo.cfg
      - ./config/zoo/zookeeper-1/data:/data
      - ./config/zoo/zookeeper-1/datalog:/datalog
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zookeeper-1:2888:3888 server.2=zookeeper-2:2888:3888 server.3=zookeeper-3:2888:3888

  zookeeper-2:
    image: localhost:5000/zookeeper
    container_name: zookeeper-2
    hostname: zookeeper-2
    restart: always
    networks:
      - clickhouse-net
    ports:
      - "21812:2181"
    volumes:
      - ./config/zoo/zoo.cfg:/conf/zoo.cfg
      - ./config/zoo/zookeeper-2/data:/data
      - ./config/zoo/zookeeper-2/datalog:/datalog
    environment:
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=zookeeper-1:2888:3888 server.2=zookeeper-2:2888:3888 server.3=zookeeper-3:2888:3888

  zookeeper-3:
    image: localhost:5000/zookeeper
    container_name: zookeeper-3
    hostname: zookeeper-3
    restart: always
    networks:
      - clickhouse-net
    ports:
      - "21813:2181"
    volumes:
      - ./config/zoo/zoo.cfg:/conf/zoo.cfg
      - ./config/zoo/zookeeper-3/data:/data
      - ./config/zoo/zookeeper-3/datalog:/datalog
    environment:
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=zookeeper-1:2888:3888 server.2=zookeeper-2:2888:3888 server.3=zookeeper-3:2888:3888

  # ===========================
  # ✅ ClickHouse Cluster (4 Nodes)
  # ===========================
  clickhouse-01:
    image: localhost:5000/clickhouse
    hostname: clickhouse-01
    container_name: clickhouse-01
    restart: always
    ports:
      - "9001:9000"
      - "8123:8123"
    environment:
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=admin123
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    volumes:
      - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
      - ./config/users.xml:/etc/clickhouse-server/users.xml
      - /mnt/wsl/data/server-01:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - clickhouse-net
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3

  clickhouse-02:
    image: localhost:5000/clickhouse
    hostname: clickhouse-02
    container_name: clickhouse-02
    restart: always
    ports:
      - "9002:9000"
      - "8124:8123"
    environment:
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=admin123
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    volumes:
      - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
      - ./config/users.xml:/etc/clickhouse-server/users.xml
      - /mnt/wsl/data/server-02:/var/lib/clickhouse
    networks:
      - clickhouse-net
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3

  clickhouse-03:
    image: localhost:5000/clickhouse
    hostname: clickhouse-03
    container_name: clickhouse-03
    restart: always
    ports:
      - "9003:9000"
      - "8125:8123"
    environment:
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=admin123
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    volumes:
      - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
      - ./config/users.xml:/etc/clickhouse-server/users.xml
      - /mnt/wsl/data/server-03:/var/lib/clickhouse
    networks:
      - clickhouse-net
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3

  clickhouse-04:
    image: localhost:5000/clickhouse
    hostname: clickhouse-04
    container_name: clickhouse-04
    restart: always
    ports:
      - "9004:9000"
      - "8126:8123"
    environment:
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=admin123
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    volumes:
      - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
      - ./config/users.xml:/etc/clickhouse-server/users.xml
      - /mnt/wsl/data/server-04:/var/lib/clickhouse
    networks:
      - clickhouse-net
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3

  # ===========================
  # ✅ SeaweedFS for Storage
  # ===========================
  seaweedfs-master:
    image: localhost:5000/seaweedfs
    command: "master -ip=seaweedfs-master -port=9333"
    container_name: seaweedfs-master
    hostname: seaweedfs-master
    restart: always
    ports:
      - "9333:9333"
    volumes:
      - ./data/seaweedfs-master:/data
    networks:
      - clickhouse-net

  seaweedfs-volume:
    image: localhost:5000/seaweedfs
    command: "volume -mserver=seaweedfs-master:9333 -port=8080 -dir=/data"
    container_name: seaweedfs-volume
    hostname: seaweedfs-volume
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./data/seaweedfs-volume:/data
    depends_on:
      - seaweedfs-master
    networks:
      - clickhouse-net

  # ===========================
  # ✅ Victoria Metrics for Monitoring
  # ===========================
  victoria-metrics:
    image: localhost:5000/victoria
    container_name: victoria-metrics
    hostname: victoria-metrics
    restart: always
    ports:
      - "8428:8428"
    volumes:
      - ./data/victoria-metrics:/storage
    command:
      - "-storageDataPath=/storage"
    networks:
      - clickhouse-net

  # ===========================
  # ✅ Grafana for Dashboard
  # ===========================
  grafana:
    image: localhost:5000/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - clickhouse-01
      - clickhouse-02
      - victoria-metrics
    networks:
      - clickhouse-net

networks:
  clickhouse-net:
    external: true

volumes:
  grafana_data:
  victoria-metrics-data:
